import { Animal } from "../animal-engine/animals";

export const ANIMALS: Animal[] = [

    {
        id: 789,
        name: 'Unicorn',
        description: 'The Unicorn. The Unicorn is a mythical horse-like beast, with a horn attached on its forehead. Unicorns can live to be hundreds, perhaps even thousands of years old if left untouched by evil hands. There is little genuine fact known about the animal, due to it being mainly a creature of myth and legend.',
        age: 1,
        experienceNeeded: 50,
        currentExperience: 0,
        lvl: 1,
        beauty: 10,
        happiness: 100,
        intelligence: 80,
        speed: 100,
        str: 25,
        img: 'assets/unicorn.jpg',
        icon: '.assets/unicorn-icon.jpg',
        upgradeCost: 1000,
        selected: false,
    },
    {
        id: 101112,
        name: 'Hippogriff',
        description: 'A Hippogriff is a magical beast that has the front legs, wings, and head of a giant eagle and the body, hind legs and tail of a horse. It is very similar to another magical creature, the Griffin, with the horse rear replacing the lion rear.',
        age: 1,
        experienceNeeded: 50,
        currentExperience: 0,
        lvl: 1,
        beauty: 10,
        happiness: 100,
        intelligence: 80,
        speed: 100,
        str: 25,
        img: 'assets/hypogriff.jpg',
        icon: 'assets/hypogriff-icon.jpg',
        upgradeCost: 1000,
        selected: false,
    },
    {
        id: 131415,
        name: 'Dragon',
        description: 'Dragon, legendary monster usually conceived as a huge, bat-winged, fire-breathing, scaly lizard or snake with a barbed tail. The belief in these creatures apparently arose without the slightest knowledge on the part of the ancients of the gigantic, prehistoric, dragon-like reptiles.',
        age: 1,
        experienceNeeded: 50,
        currentExperience: 0,
        lvl: 1,
        beauty: 10,
        happiness: 100,
        intelligence: 80,
        speed: 100,
        str: 25,
        img: 'assets/dragon.jpg',
        icon: 'assets/dragon-icon.jpg',
        upgradeCost: 1000,
        selected: false,
    },


];
