import { Animal } from "../animal-engine/animals";

export const ANIMALS: Animal[] = [

    {
        id: 789,
        name: 'Unicorn',
        description: '',
        age: 1,
        evolveLvl: 0,
        experienceNeeded: 50,
        currentExperience: 0,
        lvl: 1,
        currentLvl: 0,
        beauty: 10,
        happiness: 100,
        intelligence: 80,
        speed: 100,
        str: 25,
        img: 'assets/animals/Crystal1.png',
        icon: 'assets/animals/Crystal1.png',
        upgradeCost: 1000,
        selected: false,
        evolve: false,
    },
    {
        id: 101112,
        name: 'Hippogriph',
        description: '',
        age: 1,
        evolveLvl: 0,
        experienceNeeded: 50,
        currentExperience: 0,
        lvl: 1,
        currentLvl: 0,
        beauty: 10,
        happiness: 100,
        intelligence: 80,
        speed: 100,
        str: 25,
        img: 'assets/animals/Crystal2.png',
        icon: 'assets/animals/Crystal2.png',
        upgradeCost: 1000,
        selected: false,
        evolve: false,
    },
    {
        id: 131415,
        name: 'Dragon',
        description: '',
        age: 1,
        evolveLvl: 0,
        experienceNeeded: 50,
        currentExperience: 0,
        lvl: 1,
        currentLvl: 0,
        beauty: 10,
        happiness: 100,
        intelligence: 80,
        speed: 100,
        str: 25,
        img: 'assets/animals/Crystal3.png',
        icon: 'assets/animals/Crystal3.png',
        upgradeCost: 1000,
        selected: false,
        evolve: false,
    },


];
